In [1]:
import networkx as nx
import plotly as ply
import numpy as np
import sympy as sym

In [2]:
def norepet(cycle):
    ret =True
    NewList =[]
    for a in cycle:
        if a not in NewList:
            NewList.append(a)
        else:
            return False
    return ret
def inrange(cycle,min, max):
    ret =True
    for a in cycle:
        if a < min:
            return False
        elif a > max:
            return False
        if not(a%1 ==0):
            return False
    return ret

In [3]:
#c6
#2n +1 -(v+e) ≤ k ≤ 2(v+e) -2n
#-7≤k≤ 20

In [4]:
array=[]
x=3
e=x
n=1
for v in range(0,x):
    block = []
    for i in range(0,3*x +2):
        block.append(0)
    block[v] = -1
    block[e] = 1
    block[-2] = -1
    if n == x+1:
        block[-1]= 1
    else:
        block[-1] = n
    array.append(block)
    e+=1
    n+=1
    block = []
    for i in range(0,3*x +2):
        block.append(0)
    block[v] = -1
    block[e] = 1
    block[-2] = -1
    if n ==x+1:
        block[-1] =1
    else:
        block[-1]=n
    array.append(block)
    e+=1


In [5]:
#               v2,4,6,1,2,3,4,5,6,k,c
M = np.matrix(array)
print(M)       
M_rref =sym.Matrix(M).rref()
print(M_rref)

[[-1  0  0  1  0  0  0  0  0 -1  1]
 [-1  0  0  0  1  0  0  0  0 -1  2]
 [ 0 -1  0  0  0  1  0  0  0 -1  2]
 [ 0 -1  0  0  0  0  1  0  0 -1  3]
 [ 0  0 -1  0  0  0  0  1  0 -1  3]
 [ 0  0 -1  0  0  0  0  0  1 -1  1]]
(Matrix([
[1, 0, 0, 0, -1, 0,  0, 0,  0, 1, -2],
[0, 1, 0, 0,  0, 0, -1, 0,  0, 1, -3],
[0, 0, 1, 0,  0, 0,  0, 0, -1, 1, -1],
[0, 0, 0, 1, -1, 0,  0, 0,  0, 0, -1],
[0, 0, 0, 0,  0, 1, -1, 0,  0, 0, -1],
[0, 0, 0, 0,  0, 0,  0, 1, -1, 0,  2]]), (0, 1, 2, 3, 5, 7))


In [6]:
count = 0
for k in range(-7,21):
    for e2 in range(1,13):
        v2 = e2 -k +2
        e1 = e2+1
        cycle = [1,2,3,v2,e1,e2]
        if not(norepet(cycle) and inrange(cycle,1, 12)):
            continue
        for e4 in range(1,13):
            v4 = e4 -k +3
            e3 = e4+1
            cycle = [1,2,3,v2,v4,e1,e2,e3,e4]
            if not(norepet(cycle) and inrange(cycle,1, 12)):
                continue
            for e6 in range(1,13):
                v6 = e6 -k +1
                e5 = e6-2
                cycle = [1,2,3,v2,v4,v6,e1,e2,e3,e4,e5,e6]
                if not(norepet(cycle) and inrange(cycle,1, 12)):
                    continue 
                print([[1,2,3],[v2,v4,v6],[e1,e2,e3,e4,e5,e6]],"k= ",k)
                count +=1
print(count)

[[1, 2, 3], [6, 10, 12], [5, 4, 8, 7, 9, 11]] k=  0
[[1, 2, 3], [12, 7, 9], [11, 10, 5, 4, 6, 8]] k=  0
[[1, 2, 3], [6, 10, 4], [9, 8, 12, 11, 5, 7]] k=  4
[[1, 2, 3], [9, 4, 7], [12, 11, 6, 5, 8, 10]] k=  4
4


In [7]:
# end of c6

In [8]:
#c8
#2n +1 -(v+e) ≤ k ≤ 2(v+e) -2n
#-11≤ k≤ 28

In [9]:
array=[]
x=4
e=x
n=1
for v in range(0,x):
    block = []
    for i in range(0,3*x +2):
        block.append(0)
    block[v] = -1
    block[e] = 1
    block[-2] = -1
    if n == x+1:
        block[-1]= 1
    else:
        block[-1] = n
    array.append(block)
    e+=1
    n+=1
    block = []
    for i in range(0,3*x +2):
        block.append(0)
    block[v] = -1
    block[e] = 1
    block[-2] = -1
    if n ==x+1:
        block[-1] =1
    else:
        block[-1]=n
    array.append(block)
    e+=1
M = np.matrix(array)
print(M)       
M_rref =sym.Matrix(M).rref()
print(M_rref)

[[-1  0  0  0  1  0  0  0  0  0  0  0 -1  1]
 [-1  0  0  0  0  1  0  0  0  0  0  0 -1  2]
 [ 0 -1  0  0  0  0  1  0  0  0  0  0 -1  2]
 [ 0 -1  0  0  0  0  0  1  0  0  0  0 -1  3]
 [ 0  0 -1  0  0  0  0  0  1  0  0  0 -1  3]
 [ 0  0 -1  0  0  0  0  0  0  1  0  0 -1  4]
 [ 0  0  0 -1  0  0  0  0  0  0  1  0 -1  4]
 [ 0  0  0 -1  0  0  0  0  0  0  0  1 -1  1]]
(Matrix([
[1, 0, 0, 0, 0, -1, 0,  0, 0,  0, 0,  0, 1, -2],
[0, 1, 0, 0, 0,  0, 0, -1, 0,  0, 0,  0, 1, -3],
[0, 0, 1, 0, 0,  0, 0,  0, 0, -1, 0,  0, 1, -4],
[0, 0, 0, 1, 0,  0, 0,  0, 0,  0, 0, -1, 1, -1],
[0, 0, 0, 0, 1, -1, 0,  0, 0,  0, 0,  0, 0, -1],
[0, 0, 0, 0, 0,  0, 1, -1, 0,  0, 0,  0, 0, -1],
[0, 0, 0, 0, 0,  0, 0,  0, 1, -1, 0,  0, 0, -1],
[0, 0, 0, 0, 0,  0, 0,  0, 0,  0, 1, -1, 0,  3]]), (0, 1, 2, 3, 4, 6, 8, 10))


In [10]:
count = 0
for k in range(-11,29):
    for e2 in range (1,17):
        v2 = e2 -k +2
        e1 = e2+1
        cycle = [1,2,3,4,v2,e1,e2]
        if not(norepet(cycle) and inrange(cycle,1, 16)):
            continue
        for e4 in range(1,17):
            v4= e4 -k +3
            e3 = e4 +1
            cycle = [1,2,3,4,v2,v4,e1,e2,e3,e4]
            if not(norepet(cycle) and inrange(cycle,1, 16)):
                continue
            for e6 in range(1,17):
                v6 = e6 -k +4
                e5 =e6 +1
                cycle = [1,2,3,4,v2,v4,v6,e1,e2,e3,e4,e5,e6]
                if not(norepet(cycle) and inrange(cycle,1, 16)):
                    continue
                for e8 in range(1,17):
                    v8 =e8 -k +1
                    e7 = e8 -3
                    cycle = [1,2,3,4,v2,v4,v6,v8,e1,e2,e3,e4,e5,e6,e7,e8]
                    if not(norepet(cycle) and inrange(cycle,1, 16)):
                        continue
                    count +=1
                    print([[1,2,3,4],[v2,v4,v6,v8],[e1,e2,e3,e4,e5,e6,e7,e8]],"k= ",k)
print("count", count)

count 0


In [11]:
#end of c8

In [12]:
# c10
#2n +1 -(v+e) ≤ k ≤ 2(v+e) -2n
# -15≤ k ≤ 36

In [13]:
array=[]
x=5
e=x
n=1
for v in range(0,x):
    block = []
    for i in range(0,3*x +2):
        block.append(0)
    block[v] = -1
    block[e] = 1
    block[-2] = -1
    if n == x+1:
        block[-1]= 1
    else:
        block[-1] = n
    array.append(block)
    e+=1
    n+=1
    block = []
    for i in range(0,3*x +2):
        block.append(0)
    block[v] = -1
    block[e] = 1
    block[-2] = -1
    if n ==x+1:
        block[-1] =1
    else:
        block[-1]=n
    array.append(block)
    e+=1
M = np.matrix(array)
print(M)       
M_rref =sym.Matrix(M).rref()
print(M_rref)

[[-1  0  0  0  0  1  0  0  0  0  0  0  0  0  0 -1  1]
 [-1  0  0  0  0  0  1  0  0  0  0  0  0  0  0 -1  2]
 [ 0 -1  0  0  0  0  0  1  0  0  0  0  0  0  0 -1  2]
 [ 0 -1  0  0  0  0  0  0  1  0  0  0  0  0  0 -1  3]
 [ 0  0 -1  0  0  0  0  0  0  1  0  0  0  0  0 -1  3]
 [ 0  0 -1  0  0  0  0  0  0  0  1  0  0  0  0 -1  4]
 [ 0  0  0 -1  0  0  0  0  0  0  0  1  0  0  0 -1  4]
 [ 0  0  0 -1  0  0  0  0  0  0  0  0  1  0  0 -1  5]
 [ 0  0  0  0 -1  0  0  0  0  0  0  0  0  1  0 -1  5]
 [ 0  0  0  0 -1  0  0  0  0  0  0  0  0  0  1 -1  1]]
(Matrix([
[1, 0, 0, 0, 0, 0, -1, 0,  0, 0,  0, 0,  0, 0,  0, 1, -2],
[0, 1, 0, 0, 0, 0,  0, 0, -1, 0,  0, 0,  0, 0,  0, 1, -3],
[0, 0, 1, 0, 0, 0,  0, 0,  0, 0, -1, 0,  0, 0,  0, 1, -4],
[0, 0, 0, 1, 0, 0,  0, 0,  0, 0,  0, 0, -1, 0,  0, 1, -5],
[0, 0, 0, 0, 1, 0,  0, 0,  0, 0,  0, 0,  0, 0, -1, 1, -1],
[0, 0, 0, 0, 0, 1, -1, 0,  0, 0,  0, 0,  0, 0,  0, 0, -1],
[0, 0, 0, 0, 0, 0,  0, 1, -1, 0,  0, 0,  0, 0,  0, 0, -1],
[0, 0, 0, 0, 0, 0,  0, 0,  0, 1, -1,

In [14]:
count =0
for k in range(-15,37):
    for e2 in range(1,21):
        v2 = e2 -k +2
        e1 = e2+1
        cycle = [1,2,3,4,5,v2,e1,e2]
        if not(norepet(cycle) and inrange(cycle,1, 20)):
            continue
        for e4 in range(1,21):
            v4= e4 -k +3
            e3 = e4 +1
            cycle = [1,2,3,4,5,v2,v4,e1,e2,e3,e4]
            if not(norepet(cycle) and inrange(cycle,1, 20)):
                continue
            for e6 in range(1,21):
                v6 = e6 -k +4
                e5 =e6 +1
                cycle = [1,2,3,4,5,v2,v4,v6,e1,e2,e3,e4,e5,e6]
                if not(norepet(cycle) and inrange(cycle,1, 20)):
                    continue
                for e8 in range(1,21):
                    v8 =e8 -k +5
                    e7 = e8 +1
                    cycle = [1,2,3,4,5,v2,v4,v6,v8,e1,e2,e3,e4,e5,e6,e7,e8]
                    if not(norepet(cycle) and inrange(cycle,1, 20)):
                        continue
                    for e10 in range(1,21):
                        v10 = e10 -k +1
                        e9 = e10 -4
                        cycle = [1,2,3,4,5,v2,v4,v6,v8,v10,e1,e2,e3,e4,e5,e6,e7,e8,e9,e10]
                        if not(norepet(cycle) and inrange(cycle,1, 20)):
                            continue
                        count +=1
                        print([[1,2,3,4,5],[v2,v4,v6,v8,v10],[e1,e2,e3,e4,e5,e6,e7,e8,e9,e10]],
                              "k= ", k)
print("count = ", count)

[[1, 2, 3, 4, 5], [9, 20, 16, 19, 11], [8, 7, 18, 17, 13, 12, 15, 14, 6, 10]] k=  0
[[1, 2, 3, 4, 5], [10, 15, 20, 11, 19], [9, 8, 13, 12, 17, 16, 7, 6, 14, 18]] k=  0
[[1, 2, 3, 4, 5], [18, 14, 10, 13, 20], [17, 16, 12, 11, 7, 6, 9, 8, 15, 19]] k=  0
[[1, 2, 3, 4, 5], [19, 9, 14, 20, 13], [18, 17, 7, 6, 11, 10, 16, 15, 8, 12]] k=  0
[[1, 2, 3, 4, 5], [6, 12, 17, 7, 13], [11, 10, 16, 15, 20, 19, 9, 8, 14, 18]] k=  6
[[1, 2, 3, 4, 5], [7, 10, 6, 17, 15], [12, 11, 14, 13, 9, 8, 19, 18, 16, 20]] k=  6
[[1, 2, 3, 4, 5], [13, 16, 12, 8, 6], [18, 17, 20, 19, 15, 14, 10, 9, 7, 11]] k=  6
[[1, 2, 3, 4, 5], [15, 6, 11, 16, 7], [20, 19, 10, 9, 14, 13, 18, 17, 8, 12]] k=  6
count =  8


In [15]:
#end of c10

In [16]:
# c12
#2n +1 -(v+e) ≤ k ≤ 2(v+e) -2n
#-19 ≤ k≤ 44

In [17]:
array=[]
x=6
e=x
n=1
for v in range(0,x):
    block = []
    for i in range(0,3*x +2):
        block.append(0)
    block[v] = -1
    block[e] = 1
    block[-2] = -1
    if n == x+1:
        block[-1]= 1
    else:
        block[-1] = n
    array.append(block)
    e+=1
    n+=1
    block = []
    for i in range(0,3*x +2):
        block.append(0)
    block[v] = -1
    block[e] = 1
    block[-2] = -1
    if n ==x+1:
        block[-1] =1
    else:
        block[-1]=n
    array.append(block)
    e+=1
M = np.matrix(array)
print(M)       
M_rref =sym.Matrix(M).rref()
print(M_rref)

[[-1  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0 -1  1]
 [-1  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0 -1  2]
 [ 0 -1  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0 -1  2]
 [ 0 -1  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0 -1  3]
 [ 0  0 -1  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0 -1  3]
 [ 0  0 -1  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0 -1  4]
 [ 0  0  0 -1  0  0  0  0  0  0  0  0  1  0  0  0  0  0 -1  4]
 [ 0  0  0 -1  0  0  0  0  0  0  0  0  0  1  0  0  0  0 -1  5]
 [ 0  0  0  0 -1  0  0  0  0  0  0  0  0  0  1  0  0  0 -1  5]
 [ 0  0  0  0 -1  0  0  0  0  0  0  0  0  0  0  1  0  0 -1  6]
 [ 0  0  0  0  0 -1  0  0  0  0  0  0  0  0  0  0  1  0 -1  6]
 [ 0  0  0  0  0 -1  0  0  0  0  0  0  0  0  0  0  0  1 -1  1]]
(Matrix([
[1, 0, 0, 0, 0, 0, 0, -1, 0,  0, 0,  0, 0,  0, 0,  0, 0,  0, 1, -2],
[0, 1, 0, 0, 0, 0, 0,  0, 0, -1, 0,  0, 0,  0, 0,  0, 0,  0, 1, -3],
[0, 0, 1, 0, 0, 0, 0,  0, 0,  0, 0, -1, 0,  0, 0,  0, 0,  0, 1, -4],
[0, 0, 0, 1, 0, 0, 0,  0, 

In [18]:
count =0
for k in range(-19, 45):
    for e2 in range(1,25):
        v2 = e2 -k +2
        e1 = e2+1
        cycle = [1,2,3,4,5,6,v2,e1,e2]
        if not(norepet(cycle) and inrange(cycle,1, 24)):
            continue
        for e4 in range(1,25):
            v4= e4 -k +3
            e3 = e4 +1
            cycle = [1,2,3,4,5,6,v2,v4,e1,e2,e3,e4]
            if not(norepet(cycle) and inrange(cycle,1, 24)):
                continue
            for e6 in range(1,25):
                v6 = e6 -k +4
                e5 =e6 +1
                cycle = [1,2,3,4,5,6,v2,v4,v6,e1,e2,e3,e4,e5,e6]
                if not(norepet(cycle) and inrange(cycle,1, 24)):
                    continue
                for e8 in range(1,25):
                    v8 =e8 -k +5
                    e7 = e8 +1
                    cycle = [1,2,3,4,5,6,v2,v4,v6,v8,e1,e2,e3,e4,e5,e6,e7,e8]
                    if not(norepet(cycle) and inrange(cycle,1, 24)):
                        continue
                    for e10 in range(1,25):
                        v10 = e10 -k +6
                        e9 = e10 -4
                        cycle = [1,2,3,4,5,6,v2,v4,v6,v8,v10,e1,e2,e3,e4,e5,e6,e7,e8,e9,e10]
                        if not(norepet(cycle) and inrange(cycle,1, 24)):
                            continue
                        for e12 in range(1,25):
                            v12 = e12 -k +1
                            e11 = e12 -5
                            cycle = [1,2,3,4,5,6,v2,v4,v6,v8,v10,v12
                                     ,e1,e2,e3,e4,e5,e6,e7,e8,e9,e10,e11,e12]
                            if not(norepet(cycle) and inrange(cycle,1, 24)):
                                continue
                            count += 1
                            print([[1,2,3,4,5,6],[v2,v4,v6,v8,v10,v12],
                                   [e1,e2,e3,e4,e5,e6,e7,e8,e9,e10,e11,e12]], "k = ",k)
print(count)

0


In [19]:
#end of c12

In [20]:
#c14
#2n +1 -(v+e) ≤ k ≤ 2(v+e) -2n
# -23 ≤ k ≤ 52

In [21]:
array=[]
x=7
e=x
n=1
for v in range(0,x):
    block = []
    for i in range(0,3*x +2):
        block.append(0)
    block[v] = -1
    block[e] = 1
    block[-2] = -1
    if n == x+1:
        block[-1]= 1
    else:
        block[-1] = n
    array.append(block)
    e+=1
    n+=1
    block = []
    for i in range(0,3*x +2):
        block.append(0)
    block[v] = -1
    block[e] = 1
    block[-2] = -1
    if n ==x+1:
        block[-1] =1
    else:
        block[-1]=n
    array.append(block)
    e+=1
M = np.matrix(array)
print(M)       
M_rref =sym.Matrix(M).rref()
print(M_rref)

[[-1  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0 -1  1]
 [-1  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0 -1  2]
 [ 0 -1  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0 -1  2]
 [ 0 -1  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0 -1  3]
 [ 0  0 -1  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0 -1  3]
 [ 0  0 -1  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0 -1  4]
 [ 0  0  0 -1  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0 -1  4]
 [ 0  0  0 -1  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0 -1  5]
 [ 0  0  0  0 -1  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0 -1  5]
 [ 0  0  0  0 -1  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0 -1  6]
 [ 0  0  0  0  0 -1  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0 -1  6]
 [ 0  0  0  0  0 -1  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0 -1  7]
 [ 0  0  0  0  0  0 -1  0  0  0  0  0  0  0  0  0  0  0  0  1  0 -1  7]
 [ 0  0  0  0  0  0 -1  0  0  0  0  0  0  0  0  0  0  0  0  0  1

In [22]:
count =0
for k in range(-23, 53):
    for e2 in range(1,29):
        v2 = e2 -k +2
        e1 = e2+1
        cycle = [1,2,3,4,5,6,7,v2,e1,e2]
        if not(norepet(cycle) and inrange(cycle,1, 28)):
            continue
        for e4 in range(1,29):
            v4= e4 -k +3
            e3 = e4 +1
            cycle = [1,2,3,4,5,6,7,v2,v4,e1,e2,e3,e4]
            if not(norepet(cycle) and inrange(cycle,1, 28)):
                continue
            for e6 in range(1,29):
                v6 = e6 -k +4
                e5 =e6 +1
                cycle = [1,2,3,4,5,6,7,v2,v4,v6,e1,e2,e3,e4,e5,e6]
                if not(norepet(cycle) and inrange(cycle,1, 28)):
                    continue
                for e8 in range(1,29):
                    v8 =e8 -k +5
                    e7 = e8 +1
                    cycle = [1,2,3,4,5,6,7,v2,v4,v6,v8,e1,e2,e3,e4,e5,e6,e7,e8]
                    if not(norepet(cycle) and inrange(cycle,1, 28)):
                        continue
                    for e10 in range(1,29):
                        v10 = e10 -k +6
                        e9 = e10 +1
                        cycle = [1,2,3,4,5,6,7,v2,v4,v6,v8,v10,e1,e2,e3,e4,e5,e6,e7,e8,e9,e10]
                        if not(norepet(cycle) and inrange(cycle,1, 28)):
                            continue
                        for e12 in range(1,29):
                            v12 = e12 -k +7
                            e11 = e12 +1
                            cycle = [1,2,3,4,5,6,7,v2,v4,v6,v8,v10,v12,
                                     e1,e2,e3,e4,e5,e6,e7,e8,e9,e10,e11,e12]
                            if not(norepet(cycle) and inrange(cycle,1, 28)):
                                continue
                            for e14 in range(1,29):
                                v14 = e14 -k +1
                                e13 = e14 - 6
                                cycle = [1,2,3,4,5,6,7,v2,v4,v6,v8,v10,v12,v14
                                     ,e1,e2,e3,e4,e5,e6,e7,e8,e9,e10,e11,e12,e13,e14]
                                if not(norepet(cycle) and inrange(cycle,1, 28)):
                                    continue
                                count += 1
                                print([[1,2,3,4,5,6,7],[v2,v4,v6,v8,v10,v12,v14]])
                                print([e1,e2,e3,e4,e5,e6,e7,e8,e9,e10,e11,e12,e13,e14])
                                print("k =",k)
print(count)

[[1, 2, 3, 4, 5, 6, 7], [12, 15, 28, 26, 21, 25, 27]]
[9, 8, 11, 10, 23, 22, 20, 19, 14, 13, 17, 16, 18, 24]
k = -2
[[1, 2, 3, 4, 5, 6, 7], [26, 15, 14, 19, 28, 25, 27]]
[23, 22, 11, 10, 9, 8, 13, 12, 21, 20, 17, 16, 18, 24]
k = -2
[[1, 2, 3, 4, 5, 6, 7], [26, 17, 14, 27, 18, 24, 28]]
[23, 22, 13, 12, 9, 8, 21, 20, 11, 10, 16, 15, 19, 25]
k = -2
[[1, 2, 3, 4, 5, 6, 7], [27, 15, 14, 19, 28, 26, 25]]
[24, 23, 11, 10, 9, 8, 13, 12, 21, 20, 18, 17, 16, 22]
k = -2
[[1, 2, 3, 4, 5, 6, 7], [28, 15, 27, 19, 16, 26, 23]]
[25, 24, 11, 10, 22, 21, 13, 12, 9, 8, 18, 17, 14, 20]
k = -2
[[1, 2, 3, 4, 5, 6, 7], [10, 8, 17, 22, 21, 9, 11]]
[19, 18, 16, 15, 24, 23, 28, 27, 26, 25, 13, 12, 14, 20]
k = 10
[[1, 2, 3, 4, 5, 6, 7], [10, 20, 17, 9, 21, 8, 13]]
[19, 18, 28, 27, 24, 23, 15, 14, 26, 25, 12, 11, 16, 22]
k = 10
[[1, 2, 3, 4, 5, 6, 7], [11, 8, 17, 22, 21, 10, 9]]
[20, 19, 16, 15, 24, 23, 28, 27, 26, 25, 14, 13, 12, 18]
k = 10
[[1, 2, 3, 4, 5, 6, 7], [11, 15, 10, 8, 21, 24, 9]]
[20, 19, 23, 22, 17,

In [23]:
# c18
#2n +1 -(v+e) ≤ k ≤ 2(v+e) -2n
#-31 ≤ k≤ 68

In [24]:
array=[]
x=9
e=x
n=1
for v in range(0,x):
    block = []
    for i in range(0,3*x +2):
        block.append(0)
    block[v] = -1
    block[e] = 1
    block[-2] = -1
    if n == x+1:
        block[-1]= 1
    else:
        block[-1] = n
    array.append(block)
    e+=1
    n+=1
    block = []
    for i in range(0,3*x +2):
        block.append(0)
    block[v] = -1
    block[e] = 1
    block[-2] = -1
    if n ==x+1:
        block[-1] =1
    else:
        block[-1]=n
    array.append(block)
    e+=1
M = np.matrix(array)
print(M)       
M_rref =sym.Matrix(M).rref()
print(M_rref)

[[-1  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0 -1  1]
 [-1  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0 -1  2]
 [ 0 -1  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0 -1  2]
 [ 0 -1  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0
   0  0  0 -1  3]
 [ 0  0 -1  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0
   0  0  0 -1  3]
 [ 0  0 -1  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0
   0  0  0 -1  4]
 [ 0  0  0 -1  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0
   0  0  0 -1  4]
 [ 0  0  0 -1  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0
   0  0  0 -1  5]
 [ 0  0  0  0 -1  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0
   0  0  0 -1  5]
 [ 0  0  0  0 -1  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0
   0  0  0 -1  6]
 [ 0  0  0  0  0 -1  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0
   0  

In [ ]:
count =0
ve= 36
for k in range(-31, 68):
    print(k)
    for e2 in range(1,ve+1):
        v2 = e2 -k +2
        e1 = e2+1
        cycle = [1,2,3,4,5,6,7,8,9,v2,e1,e2]
        if not(norepet(cycle) and inrange(cycle,1, ve)):
            continue
        for e4 in range(1,ve+1):
            v4= e4 -k +3
            e3 = e4 +1
            cycle = [1,2,3,4,5,6,7,8,9,v2,v4,e1,e2,e3,e4]
            if not(norepet(cycle) and inrange(cycle,1, ve)):
                continue
            for e6 in range(1,ve+1):
                v6 = e6 -k +4
                e5 =e6 +1
                cycle = [1,2,3,4,5,6,7,8,9,v2,v4,v6,e1,e2,e3,e4,e5,e6]
                if not(norepet(cycle) and inrange(cycle,1, ve)):
                    continue
                for e8 in range(1,ve+1):
                    v8 =e8 -k +5
                    e7 = e8 +1
                    cycle = [1,2,3,4,5,6,7,8,9,v2,v4,v6,v8,e1,e2,e3,e4,e5,e6,e7,e8]
                    if not(norepet(cycle) and inrange(cycle,1, ve)):
                        continue
                    for e10 in range(1,ve+1):
                        v10 = e10 -k +6
                        e9 = e10 +1
                        cycle = [1,2,3,4,5,6,7,8,9,v2,v4,v6,v8,v10,e1,e2,e3,e4,e5,e6,e7,e8,e9,e10]
                        if not(norepet(cycle) and inrange(cycle,1, ve)):
                            continue
                        for e12 in range(1,ve+1):
                            v12 = e12 -k +7
                            e11 = e12 +1
                            cycle = [1,2,3,4,5,6,7,8,9,v2,v4,v6,v8,v10,v12,
                                     e1,e2,e3,e4,e5,e6,e7,e8,e9,e10,e11,e12]
                            if not(norepet(cycle) and inrange(cycle,1, ve)):
                                continue
                            for e14 in range(1,ve+1):
                                v14 = e14 -k +8
                                e13 = e14 +1
                                cycle = [1,2,3,4,5,6,7,8,9,v2,v4,v6,v8,v10,v12,v14
                                     ,e1,e2,e3,e4,e5,e6,e7,e8,e9,e10,e11,e12,e13,e14]
                                if not(norepet(cycle) and inrange(cycle,1, ve)):
                                    continue
                                for e16 in range(1,ve+1):
                                    v16 = e16 -k +9
                                    e15 = e16 +1
                                    cycle = [1,2,3,4,5,6,7,8,9,v2,v4,v6,v8,v10,v12,v14,v16
                                     ,e1,e2,e3,e4,e5,e6,e7,e8,e9,e10,e11,e12,e13,e14,e15,e16]
                                    if not(norepet(cycle) and inrange(cycle,1, ve)):
                                        continue
                                    for e18 in range(1,ve+1):
                                        v18 = e18 -k +1
                                        e17 = e18 -8
                                        cycle = [1,2,3,4,5,6,7,8,9,v2,v4,v6,v8,v10,v12,v14,v16,v18
                                         ,e1,e2,e3,e4,e5,e6,e7,e8,e9,e10,e11,e12,e13,e14,e15,e16,e17,e18]
                                        if not(norepet(cycle) and inrange(cycle,1, ve)):
                                            continue
                                        print([[1,2,3,4,5,6,7,8,9],[v2,v4,v6,v8,v10,v12,v14,v16,v18]])
                                        print([e1,e2,e3,e4,e5,e6,e7,e8,e9,e10,e11,e12,e13,e14,e15,e16,e17,e18])
                                        print("k =",k)
                                        count += 1
print(count)

-31
-30
-29
-28
-27
-26
-25
-24
-23
-22
-21
-20
-19
-18
-17
-16
-15
-14
-13
-12
-11
-10
-9
-8
-7
-6
-5
-4
[[1, 2, 3, 4, 5, 6, 7, 8, 9], [36, 33, 18, 23, 22, 35, 28, 32, 34]]
[31, 30, 27, 26, 11, 10, 15, 14, 13, 12, 25, 24, 17, 16, 20, 19, 21, 29]
k = -4
[[1, 2, 3, 4, 5, 6, 7, 8, 9], [36, 35, 18, 25, 22, 34, 26, 33, 32]]
[31, 30, 29, 28, 11, 10, 17, 16, 13, 12, 24, 23, 15, 14, 21, 20, 19, 27]
k = -4
-3
[[1, 2, 3, 4, 5, 6, 7, 8, 9], [19, 16, 36, 34, 33, 22, 28, 32, 35]]
[15, 14, 11, 10, 30, 29, 27, 26, 25, 24, 13, 12, 18, 17, 21, 20, 23, 31]
k = -3
[[1, 2, 3, 4, 5, 6, 7, 8, 9], [19, 18, 36, 34, 33, 20, 32, 28, 35]]
[15, 14, 13, 12, 30, 29, 27, 26, 25, 24, 11, 10, 22, 21, 17, 16, 23, 31]
k = -3
[[1, 2, 3, 4, 5, 6, 7, 8, 9], [34, 16, 19, 22, 33, 36, 28, 32, 35]]
[30, 29, 11, 10, 13, 12, 15, 14, 25, 24, 27, 26, 18, 17, 21, 20, 23, 31]
k = -3
[[1, 2, 3, 4, 5, 6, 7, 8, 9], [34, 20, 19, 18, 33, 36, 32, 28, 35]]
[30, 29, 15, 14, 13, 12, 11, 10, 25, 24, 27, 26, 22, 21, 17, 16, 23, 31]
k = -3
[[1